1
js-tasks-ru/jsbasic-20230327_loseff-vladislav-vlad pull request #1
Opened 2023-04-04 19:39 UTC by Vlad-Losev

2023-04-04 19:39 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2023-04-06 11:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-06 11:20 UTC, koalex requested changes
Нужно решить задачи из 2-модуля

2023-04-06 11:20 UTC, koalex commented on 0-module/1-task/index.js
> +console.log(sum(3, 3));
Удалить `console.log`

2023-04-08 09:39 UTC, Vlad-Losev commented
/

2023-04-08 12:35 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-04-08 12:51 UTC, koalex approved these changes

2023-04-08 12:51 UTC, koalex commented on 1-module/4-task/index.js
> +  if (toLow === '1xbet now' || toLow === 'free xxxxx') {
Можно так:
`return toLow === '1xbet now' || toLow === 'free xxxxx';`

2023-04-08 12:52 UTC, merged